"""Tests for pqn-create stdin body intake (#46)."""

from __future__ import annotations

import json
from pathlib import Path

from para_quest_notes.workflows.create.cli import main


def _seed_vault(tmp_path: Path) -> Path:
    vault = tmp_path / "vault"
    for d in ("inbox", "areas", "projects", "resources", "archive"):
        (vault / d).mkdir(parents=True)
    return vault


def _config(tmp_path: Path) -> Path:
    cfg = tmp_path / "config.yaml"
    cfg.write_text(f"run_log_dir: {tmp_path / 'runs'}\n")
    return cfg


def test_stdin_body_replaces_skeleton(tmp_path: Path, capsys, monkeypatch):
    """Stdin body content replaces the default skeleton."""
    vault = _seed_vault(tmp_path)
    cfg = _config(tmp_path)
    monkeypatch.delenv("PARA_QUEST_VAULT", raising=False)
    body = "# My Project\n\nThis is my custom body content.\n"
    rc = main(
        [
            "--vault",
            str(vault),
            "--config",
            str(cfg),
            "--type",
            "project",
            "--title",
            "My Project",
            "--supports",
            "[[Health]]",
            "--body-stdin",
            "--apply",
        ],
        stdin=body,
    )
    assert rc == 0
    written = (vault / "projects/My Project.md").read_text()
    # Should contain the stdin body, not the skeleton
    assert "This is my custom body content." in written
    assert "<one-sentence purpose>" not in written
    # Frontmatter still comes first
    assert written.startswith("---\n")


def test_stdin_body_json_output(tmp_path: Path, capsys, monkeypatch):
    """JSON output works with stdin body."""
    vault = _seed_vault(tmp_path)
    cfg = _config(tmp_path)
    monkeypatch.delenv("PARA_QUEST_VAULT", raising=False)
    body = "# Notes\n\nBody from pipe.\n"
    rc = main(
        [
            "--vault",
            str(vault),
            "--config",
            str(cfg),
            "--format",
            "json",
            "--type",
            "resource",
            "--title",
            "Piped Resource",
            "--body-stdin",
        ],
        stdin=body,
    )
    payload = json.loads(capsys.readouterr().out)
    assert rc == 0
    assert payload["ok"] is True
    assert payload["plan"]["destination"] == "resources/Piped Resource.md"


def test_empty_stdin_uses_skeleton(tmp_path: Path, capsys, monkeypatch):
    """Empty stdin (whitespace-only) falls back to the skeleton."""
    vault = _seed_vault(tmp_path)
    cfg = _config(tmp_path)
    monkeypatch.delenv("PARA_QUEST_VAULT", raising=False)
    rc = main(
        [
            "--vault",
            str(vault),
            "--config",
            str(cfg),
            "--type",
            "project",
            "--title",
            "Empty Body",
            "--supports",
            "[[Health]]",
            "--body-stdin",
            "--apply",
        ],
        stdin="   \n\n  ",
    )
    assert rc == 0
    written = (vault / "projects/Empty Body.md").read_text()
    # Should use the skeleton since stdin was empty
    assert "<one-sentence purpose>" in written


def test_no_body_stdin_flag_uses_skeleton(tmp_path: Path, capsys, monkeypatch):
    """Without --body-stdin, the skeleton is used even if stdin arg provided."""
    vault = _seed_vault(tmp_path)
    cfg = _config(tmp_path)
    monkeypatch.delenv("PARA_QUEST_VAULT", raising=False)
    rc = main(
        [
            "--vault",
            str(vault),
            "--config",
            str(cfg),
            "--type",
            "project",
            "--title",
            "No Stdin",
            "--supports",
            "[[Health]]",
            "--apply",
        ],
        # stdin kwarg NOT passed, no --body-stdin flag
    )
    assert rc == 0
    written = (vault / "projects/No Stdin.md").read_text()
    assert "<one-sentence purpose>" in written


def test_stdin_body_preserves_frontmatter(tmp_path: Path, capsys, monkeypatch):
    """Stdin body doesn't interfere with canonical frontmatter generation."""
    vault = _seed_vault(tmp_path)
    cfg = _config(tmp_path)
    monkeypatch.delenv("PARA_QUEST_VAULT", raising=False)
    body = "Custom body with no frontmatter of its own.\n"
    rc = main(
        [
            "--vault",
            str(vault),
            "--config",
            str(cfg),
            "--format",
            "json",
            "--type",
            "area",
            "--title",
            "Custom Area",
            "--quest",
            "main",
            "--body-stdin",
            "--apply",
        ],
        stdin=body,
    )
    payload = json.loads(capsys.readouterr().out)
    assert rc == 0
    # Frontmatter is still generated by the workflow
    assert payload["plan"]["frontmatter"]["type"] == "area"
    assert payload["plan"]["frontmatter"]["quest"] == "main"
    # Read the file to verify
    written = (vault / "areas/Custom Area.md").read_text()
    assert "Custom body with no frontmatter" in written
    assert "type: area" in written
